# secrets.toml

GEMINI_API_KEY = "AIzaSyDTIBJY6VmCEkeWLaSQGpaEuaC1ymV_H6U"

GOOGLE_SHEETS_SPREADSHEET_ID = "1XsVFDulZvVm48TufEaVoNMkEj6-wA583lIuQz5odDiM"

[GOOGLE_CALENDAR]
CLIENT_ID = "16827486148-8lnlhbauon91di0tn0nmg7haafrenuvj.apps.googleusercontent.com"
CLIENT_SECRET = "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"
PROJECT_ID = "winning-every"
AUTH_URI = "https://accounts.google.com/o/oauth2/auth"
TOKEN_URI = "https://oauth2.googleapis.com/token"
AUTH_PROVIDER_CERT_URL = "https://www.googleapis.com/oauth2/v1/certs"
REDIRECT_URIS = "http://localhost"
CALENDAR_ID = "b78504b8f33193f9648e16015ac0f99853bacb45cfb8f07b7685834813185826@group.calendar.google.com"

[GOOGLE_SHEETS_SERVICE_ACCOUNT]
GOOGLE_TYPE = "service_account"
GOOGLE_PROJECT_ID = "winning-every"
GOOGLE_PRIVATE_KEY_ID = "261a824611f0d57fad662b1eca042fee9082e43c"
PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCeXrueZODWYyLN
ITGvh6E9E03p6CEXL86oZPkpYIE1GwylNQ5Ei/U0cwTQp7A79rUUmKkPIST3q3Ny
Ckx+aOm5kSHoh8mHWAPcDm9YhIEB7Uj56NSZTV8NbXq9JoSa/BXuX9WpYCwiTe5o
DR/bcY0W344c15HnCqSC+/HJgZu3vrOzaiaftu938SmaVxlpB3wXUUvlkjOryyWB
vRAb2viHAQL4FZXZsmSrjTKBgWcyjowPzg/4L6MdilUGhtD0qc7KsQDd0unYBo/P
o9D3q5ynBS+bDgGsUfovbett59VB7/eIwwTkpCb2E/OJJl9KC3fbQc/SxtRn0jMU
nyi7LMcb9AgMBAAECggEAF9hsOAJ47xbQseG2XTdXAf7y244J03etjmHbuUzwT3px
6jslmZEYO8w4tKEXEkRIiiAdTmufaRI96PUfhOYPkRMG77/oSnJobF0ZC1MyKIPd
mdFil22Uqw0prqrKyxo7RB/WaDEUnBqvU6fsPMqpY4EIIRQdQhQyZo2AX6ad92mo
8M8LeTgpQ1GwO7urZkPdRVGS1NL6Oe10NtSRsO1DuJsbNKOHEX4VKoJB4hqBM44L
28Yz7GuGY6jOUfN2orGLBsKIVnDLdlNJPH2d6Vsy4Op+L44Xsu6at9cQpQVRiXE9
jNiAJG6GxzDivTcVHgmbRMzj7C7PlirocEblERajCQKBgQDQxKN+YfL7CTxvlECu
kaQjTPuU4mqQu6wS4CTLJOlZ1sfw0pJ/UmZuG9vHMIy0YhA0p9K1d/sai5X18vie
vLkeG6cVtYL1f0XE+gYO3K3ftTWl2ykzWf832lzL4X3th2Q8EbhAP+ZiyRRWAPw2
TrZn876+zl0p/oTNOkrVkgYFOQKBgQDCMyfpGUDnWeT1woIhMMtLHRWZX/9GMaEn
fr1IfIuiO6OeGmpTkMtikQf2MXhnWCtj/+3RriHfU1ei/sfYkW0ghD57to4NQw0+
numE6oZtmsZrYUtC2gVMFaNxRA2VsCcglwGu5axxcxHaIqh9R+ajdBPWyXlGpS90R
Z2e85arz5QKBgCbc9DKKuVjSF1YOGxxkMFIB+rN0krHuvdGluDO441e+C+pgyLS6
+iZ1OSyTdR3/Q1UKCMePVkdSxM/MM0wZhbx9GVWJPJ/G2Y4ZnRcXLab/bMU7Tygo
EMKs+6lYiMC2+4nTIqGTQ6gQFqEL/ed+L6aaUV/juqQepUovF886J7TBAoGAFjcV
5LNv2kdNStPSYQuc5d3Q37e8kwIQZl04N/ePXaKm5+orqZ2RtpfSqlYkaOYMKKdZ
RDhARbTZ/JpasCqKqkKWhz5t55R5Cmj1wGhGR6wfg4mNuKL4pVDGiznxOzevPqpR
aGeZWf9bc+zKIm2F5KqxlJL3kn9MLbZ/hntbYAUCgYBrrN+qg5bRx8sHBGArei7D
79s4EK4O4CU++Ox5jxbaKbZZO7NZJ3sCp22Bm6OQs+RltB4gEGMLbImPKheINiVI
NFPio4qvqrKCSF05chbP0P3UTtvCFN0XOlrPiKGwsA9n009Ej7quEIQyDbaCgeJr
nmpzhBitxJ8mJ1AoBMHi4A==
-----END PRIVATE KEY-----"""
GOOGLE_CLIENT_EMAIL = "eduai-assistant@winning-every.iam.gserviceaccount.com"
GOOGLE_CLIENT_ID = "117777712446255655955"
AUTH_URI = "https://accounts.google.com/o/oauth2/auth"
TOKEN_URI = "https://oauth2.googleapis.com/token"
AUTH_PROVIDER_CERT_URL = "https://www.googleapis.com/oauth2/v1/certs"
CLIENT_CERT_URL = "https://www.googleapis.com/robot/v1/metadata/x509/eduai-assistant%40winning-every.iam.gserviceaccount.com"
UNIVERSE_DOMAIN = "googleapis.com"